### ISSUE TITLE
Please change default timeout

### ISSUE THREAD

**Issue by ghost** [akamai/AkamaiOPEN-edgegrid-php-client#20]
There is no timeout in the .edgerc, and the default SLA for our APIs is 300 seconds.  Please increase the default timeout appropriately.

This is very important, as I'm getting Travis set up to run our code.

Thanks,
Kirsten

**Comment by dshafik** [comment]
Fixed by 986de606a11591a254d8f235d6512b8078a4899d, and released in [v0.4.3](https://github.com/akamai-open/AkamaiOPEN-edgegrid-php/releases/tag/0.4.3)
