### ISSUE TITLE
Bin script rename?

### ISSUE THREAD

**Issue by siwinski** [akamai/AkamaiOPEN-edgegrid-php-client#26]
Would you be open to renaming the bin script from `http` to something like `akamai-open-edgegrid` or `akamai-edgegrid`?  I would like to package this project for [Fedora](https://getfedora.org/) but bin script `http` is too generic to provide at the system level so I will need to rename it when packaging it downstream anyway.  I was just wondering if you would be interested in a pull request with a bin script rename as well?

**Comment by ghost** [comment]
The script 'http' is not owned by our team.  Please see http://httpie.org for more information about this tool.  It probably isn't a great idea to have http use a different name on fedora, but regardless, certainly renaming it based on one specific signing library is not the right approach.  We have it available with our signing library, but many people may be using it for other things.

Other Fedora folks don't seem to have an issue with it:
https://admin.fedoraproject.org/pkgdb/package/rpms/httpie/

**Comment by siwinski** [comment]
`bin/http` is just a wrapper for your `\Akamai\Open\EdgeGrid\Cli` class.  If your bin script was just httpie I could just unbundle it and use the package you linked to, but it does not.

Per the [README for this project ](https://github.com/akamai-open/AkamaiOPEN-edgegrid-php#command-line-interface), "To aid in testing, exploration, and debugging, this library features a CLI that **mimics** httpie and provides a limited facsimile of it's capabilities as documented here."  Where is [httpie](http://httpie.org/) used?

Also, the PHAR file is named `akamai-open-edgegrid-client` and it would be nice for the bin script to match this name.

**Comment by dshafik** [comment]
@siwinski the binary in question is meant to be a facsimile for httpie's `http` when someone is unable to install httpie for whatever reason (usually because of policy, not technical reasons).

I could see renaming it to `eghttp`, but even that breaks the illusion of a drop-in replacement. Having said that, given it's differences already (see: https://github.com/akamai-open/AkamaiOPEN-edgegrid-php#command-line-interface) that might be just fine.

Do you plan on the library itself being used from a single global install? Or just the binary?

**Comment by siwinski** [comment]
@dshafik It would be a single global install via RPM.  To be completely honest though, I doubt the use cases for downstream packaging would require the bin file as the library is the important piece so if there are reservations about renaming it, no worries, I just won't package it.  My current use-cases are the [Drupal Akamai module](https://www.drupal.org/project/akamai) and some custom apps at work.

**Comment by dshafik** [comment]
@siwinski if that works for you then I'm going to close this issue. Let me know if I can help in any other way to get this packaged.
