### ISSUE TITLE
Wrong URl

### ISSUE THREAD

**Issue by iV1n5** [akamai/AkamaiOPEN-edgegrid-php-client#27]
Hi,

the link to the client file phar is wrong in the readme:

"Alternatively, download the PHAR file from the releases page."

Here is the link:
https://github.com/akamai-open/AkamaiOPEN-edgegrid-php/releases/releases - wrong
https://github.com/akamai-open/AkamaiOPEN-edgegrid-php/releases/ - correct

Could you please fix it?

Thanks.

**Comment by dshafik** [comment]
Thanks for reporting this, it has been fixed!
