### ISSUE TITLE
PHP 5.3+ is supposed to be compatible, dependencies still require 5.5+

### ISSUE THREAD

**Issue by Maltroth** [akamai/AkamaiOPEN-edgegrid-php-client#28]
Based on your releases 0.4.5/0.4.6, PHP 5.3+ should be compatible, but the dependencies still require PHP 5.5+ in composer.json. Installing your bundle via composer on a PHP 5.3 server generates an error.

**Comment by dshafik** [comment]
@Maltroth the authentication code itself is 5.3+ compatible, and can be used with cURL or any other HTTP client directly. I don't know of any way to have a composer package that works this way without using optional dependencies for the 5.5+ requirements.

I'm looking into re-working the package some now, and will keep this updated.

Thanks for your report!

**Comment by Maltroth** [comment]
Thought the whole package was 5.3 compatible, I misunderstood. Will install it manually for now!

**Comment by dshafik** [comment]
@Maltroth I made some pretty major changes and split out the signer into it's own composer package, [`akamai-open/edgegrid-auth`](https://github.com/akamai-open/AkamaiOPEN-edgegrid-php/releases) which is PHP 5.3 compatible. You may also notice this repo has been renamed (with `-client` on the end) and is now the 5.5+ compatible client only.

I also fixed some [minor] PHP 5.3 issues, mostly in the tests but also in the signer itself, so you'll want to use the new version.

I would be grateful if you could try the new package and let me know if it works for you and then I'll close out this ticket.

To use it, do:

``` sh
$ composer require akamai-open/edgegrid-auth
```

Thanks!

**Comment by Maltroth** [comment]
Installation via composer worked like a charm, thank you!

**Comment by dshafik** [comment]
Thanks @Maltroth! I'm going to close this now.
