### ISSUE TITLE
Inquiry - support of TLS 1.2

### ISSUE THREAD

**Issue by jesskuz** [akamai/AkamaiOPEN-edgegrid-php-client#30]
Just a question - will the PHP client currently support connections via **TLS 1.2** out of the box?  Thanks very much for your response.

**Comment by lkowalsk-akamai-com** [comment]
Hi, new version of this package was released today - https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/releases/tag/2.0.0 
Please take a look as it makes the package up to date
