### ISSUE TITLE
Compatibility with monolog/monolog 2.x

### ISSUE THREAD

**Issue by daniel82** [akamai/AkamaiOPEN-edgegrid-php-client#35]
Is it possible to make it compatible with monolog/monolog 2.x (https://github.com/Seldaek/monolog)

**Comment by abhisheksoni27** [comment]
Any updates on this?

**Comment by mathiasonea** [comment]
I'll tackle this one, let's see what I can achieve

**Comment by RHJasonSmith** [comment]
We've got three PRs to address this awaiting merge/approval. 

https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/pull/33/files
https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/pull/34/files
https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/pull/36/files

So this is clearly something people want. How do we get it attention?

**Comment by SiliconValet** [comment]
FWIW, our temporary workaround is to move to one of the forks. 

What are other folks doing to resolve this issue?

drupal.org/project/akamai/issues/3241404#comment-14249510

**Comment by SiliconValet** [comment]
err... both those posts/accounts (siliconvalet/rhjasonsmith) are mine. not sure why the accounts switched on me.

**Comment by lkowalsk-akamai-com** [comment]
Hi, new version of this package was released today - https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/releases/tag/2.0.0 
Please take a look as it makes the package up to date
