### ISSUE TITLE
Will this Library receive any Update again?

### ISSUE THREAD

**Issue by boredom2** [akamai/AkamaiOPEN-edgegrid-php-client#42]
We are not able to use this Library since years due to various completely outdated Dependencies and Requirements, so we have to deal with some Tricks in Composer and/or Forks. Nevertheless, we do need some APIs from Akamai, but we are thinking now it would make more sense to just write our own Code for this.

It looks a little sad, that Akamai cannot support this small Library with even one Update in four Years though, so I would like to ask - is there any chance you are updating this Library, so we can use it with PHP8+, Monolog 2+, Guzzle7+ etc again?

Thanks!

**Comment by mihaileu** [comment]
@rajiv

**Comment by lkowalsk-akamai-com** [comment]
Hi, new version of this package was released today - https://github.com/akamai/AkamaiOPEN-edgegrid-php-client/releases/tag/2.0.0 
Please take a look as it makes the package up to date
